name: List and Clean Up Maven Artifacts by Version

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - add-nightly-snapshot-release-test-ci

permissions:
  contents: read
  packages: write

jobs:
  inspect-and-clean:
    runs-on: ubuntu-latest
    steps:
      - name: Show artifacts and versions
        shell: python
        env:
          GITHUB_OWNER: krisbanas
          PACKAGE_NAME: org.quickfixj.quickfixj-messages-all
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          import os
          import requests
          import json
          from datetime import datetime, timezone, timedelta

          owner = os.getenv("GITHUB_OWNER")
          package = os.getenv("PACKAGE_NAME")
          token = os.getenv("GITHUB_TOKEN")

          headers = {
              "Accept": "application/vnd.github+json",
              "Authorization": f"Bearer {token}"
          }

          def list_versions(page=1):
              url = f"https://api.github.com/users/{owner}/packages/maven/{package}/versions?per_page=100&page={page}"
              resp = requests.get(url, headers=headers)
              if resp.status_code != 200:
                  print(f"Error listing versions: {resp.status_code}")
                  print(resp.text)
                  return []
              return resp.json()

          print("📦 Listing all package versions and their details:")

          page = 1
          while True:
              versions = list_versions(page)
              if not versions:
                  break

              for v in versions:
                  print(json.dumps(v, indent=2))

              if len(versions) < 100:
                  break
              page += 1
