name: Cleanup Old SNAPSHOTs

on:
  workflow_dispatch:      # Allows manual triggering
  push:
    branches:
      - add-nightly-snapshot-release-test-ci

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old SNAPSHOTs
        uses: actions/delete-package-versions@v5
        with:
          package-name: org.quickfixj.quickfixj-messages-all  # Replace with your package name
          package-type: 'maven'
          min-versions-to-keep: 3
          delete-only-pre-release-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}