name: Java SNAPSHOT Release

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - add-nightly-snapshot-release-test-ci
  schedule:
    - cron: '0 1 * * *'

jobs:
  release-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK & configure Maven creds
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ env.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish SNAPSHOT
        run: cat /home/runner/.m2/settings.xml